before_script:
  - docker info
  - docker-compose build

build_image:
  script:
    - docker-compose run billing_service yarn test
    - docker-compose run booking_service yarn test
    - docker-compose run catalog_service yarn test
