before_script:
  - docker-compose -f docker-compose-test.yml build

after_script:
  - docker-compose -f docker-compose-test.yml down

build_image:
  script:
    - docker-compose -f docker-compose-test.yml run billing_service yarn test
    - docker-compose -f docker-compose-test.yml run booking_service yarn test
    # - docker-compose -f docker-compose-test.yml run catalog_service yarn test
