####
# This file is used to run the tick_stack locally
# To deploy the tick_stack in docker swarm, use the "docker-stack.yml" file
#
# To deploy in CLI with your hands, use this command :
# docker-compose up -d


version: '3.2'

services:

    proxy:
        image: traefik
        command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
        networks:
            - tick_stack
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./traefik.toml:/traefik.toml"

    mongo:
        image: mongo:latest
        volumes:
            - "./.docker_volumes/mongodb:/data/db"
        ports:
            - "27017:27017"
        networks:
            - tick_stack

    mongo_express:
        image: mongo-express:latest
        ports:
            - "82:8081"
        environment:
            - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
            - "ME_CONFIG_BASICAUTH_USERNAME=etna"
            - "ME_CONFIG_BASICAUTH_PASSWORD=devops"
        networks:
            - tick_stack

    catalog_service:
        build: ./src/CatalogService
        command: nodemon --debug server.js
        volumes:
            - "./src/CatalogService:/app"
        ports:
            - "8100:3000"
        networks:
            - tick_stack

    booking_service:
        build: ./src/BookingService
        command: nodemon --debug server.js
        volumes:
            - "./src/BookingService:/app"
        ports:
            - "8200:3000"
        networks:
            - tick_stack


networks:
    tick_stack:
        driver: bridge
