---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Ensure that APT works with the https method
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - libffi-dev
    - libssl-dev

- name: Install docker GPG key
  become: true
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add docker apt repository
  become: true
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"
    state: present

- name: Update apt-cache
  become: true
  apt:
    update_cache: yes

- name: Purge the old repo if it exists
  become: true
  apt:
    name: "{{ item }}"
    purge: yes
  with_items:
    - "lxc-docker*"
    - "docker.io*"
  ignore_errors: yes

- name: Install docker package
  become: true
  apt:
    name: docker-engine
    state: present
  notify: Start Docker

- name: Add vagrant user to docker & sudo group
  become: true
  user:
    name: vagrant
    shell: /bin/bash
    groups: docker,sudo
    append: yes

- name: Install python-docker packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - htop
    - ncdu
    - curl
    - wget
    - python-docker

- name: Check if pip is installed
  stat: "path=/usr/local/bin/pip"
  register: pip_bin

- name: Download get-pip.py
  become: true
  when: not pip_bin.stat.exists
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip using get-pip.py script
  become: true
  command: "python get-pip.py"
  when: not pip_bin.stat.exists
  args:
    chdir: /tmp

- name: Install pip packages
  become: true
  pip:
    name: docker-py
    state: latest
