################################
# The registry service, required when deploy container in "Swarm Mode" to handle docker images
#

version: '3'

services:

    registry:
        image: registry:2
        deploy:
            mode: global
        ports:
            - "5000:5000"
        volumes:
            - "./.docker_volumes/registry:/var/lib/registry"
