---
- name: Builds custom services images
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    path: "{{ item.path }}"
    state: present
  with_items: "{{ service_images }}"
