---
- name: Build custom "{{ symfony_img_name }}" image
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: "{{ symfony_img_name }}"
    tag: "{{ symfony_img_tag }}"
    path: "{{ project_root_directory }}/provisioning/docker"
    state: present
