---
- name: Push official images to the local registry
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    repository: "{{ docker_registry_url }}/{{ item.name }}"
    push: yes
  with_items: "{{ docker_images }}"

- name: Push custom services images to the local registry
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    repository: "{{ docker_registry_url }}/{{ item.name }}"
    push: yes
  with_items: "{{ service_images }}"
