---
- name: Remove landscape-common package
  become: yes
  when: "'docker-nodes' in group_names"
  apt:
   name: landscape-common
   state: absent
   purge: yes

- name: Create motd file
  become: yes
  when: "'docker-nodes' in group_names"
  template:
    src: "{{ motd_file }}"
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
