---
- name: Check if GitLab configuration file already exists.
  become: true
  when: "'managers' in group_names"
  stat:
    path: "/etc/gitlab/gitlab.rb"
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  become: true
  when: "'managers' in group_names"
  stat:
    path: "/usr/bin/gitlab-ctl"
  register: gitlab_file

# Install GitLab and its dependencies.
- name: Install GitLab dependencies.
  become: true
  when: "'managers' in group_names"
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - openssh-server
    - postfix
    - curl
    - openssl

- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
    dest: "/tmp/gitlab_install_repository.sh"
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: "'managers' in group_names and gitlab_file.stat.exists == false"

- name: Install GitLab repository
  become: true
  command: bash /tmp/gitlab_install_repository.sh
  when: "'managers' in group_names and gitlab_file.stat.exists == false"

- name: Install GitLab
  become: true
  package:
    name: "{{ gitlab_edition }}"
    state: installed
  when: "'managers' in group_names and gitlab_file.stat.exists == false"

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  become: true
  when: "'managers' in group_names"
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Create GitLab SSL configuration folder.
  become: true
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: "'managers' in group_names and gitlab_create_self_signed_cert"

- name: Create self-signed certificate.
  become: true
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: "'managers' in group_names and gitlab_create_self_signed_cert"

- name: Copy GitLab configuration file.
  become: true
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
  when: "'managers' in group_names"
