---
- hosts: docker-nodes

  vars_files:
    - vars/all.yml

  roles:
    # Customize bash env of the VM for conveniences
    - bash
    - motd

    # Required Ansible Recipes :
    - docker_swarm
    - docker_registry
#    - docker_tickstack
#    - docker_traefik
