---
- name: Pull the docker "Registry" image
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: registry
    state: present
    tag: 2.6

- name: Start Registry service
  become: true
  when: "'managers' in group_names"
  docker_service:
    project_name: devops-etna
    project_src: docker
    files: docker-compose_registry.yml
    state: present
    build: no
