---
- name: Pull the docker "Registry" image
  become: true
  when: "'managers' in group_names"
  docker_image:
    name: registry
    state: present
    tag: 2

- name: Check if Registry service is running
  become: true
  when: "'managers' in group_names"
  shell: docker service ls --filter name=registry | grep '\sregistry\s' | awk '{ print $1 }'
  register: registry_created

# An error is raised if the directory not exist
- name: Create directory to persist the Registry data
  become: false
  when: "'managers' in group_names and registry_created.stdout == ''"
  file:
    path: "{{ docker_volume_directory }}/registry"
    state: directory

- name: Start the Registry service
  become: true
  when: "'managers' in group_names and registry_created.stdout == ''"
  shell: "docker service create --name registry --publish {{ docker_registry_port }}:5000 --mount type=bind,source={{ project_root_directory }}/.docker_volumes/registry,destination=/var/lib/registry --constraint 'node.role == manager' registry:2"
